version: '3'

services:
  web:
    image: llslim/docker-apache:local
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ../../workshop:/var/www/html
      - ../../archive:/var/www/archive
      - ./conf/devcerts/dockerapachephp.crt:/etc/ssl/certs/dockerapachephp.crt
      - ./conf/devcerts/dockerapachephp.key:/etc/ssl/private/dockerapachephp.key
      - ./conf/apache/sites-available:/etc/apache2/sites-available
    links:
      - php
    
  php:
    image: llslim/docker-phpfpm:local
    ports:
      - "9005:9005"
    volumes:
      - ../../workshop:/var/www/html
  db:
    image: mysql:5.7
    ports:
        - 3306:3306
    volumes:
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ../../archive/databases:/docker-entrypoint-initdb.d
  #       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myroot
    #   MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  mail:
    image: mailhog/mailhog
    ports:
      - 83:8025
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 84:80
    restart: always

  node:
    image: node:slim
    depends_on:
      - web
    volumes:
      - ../../workshop:/var/www/html
    build:
      context: .
      dockerfile: ThemeTools-build

  
    